import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Recycle, QrCode, Trophy, Gift, Leaf } from "lucide-react"

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50 leaf-pattern">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Recycle className="w-8 h-8 text-emerald-600" />
            <span className="text-2xl font-bold bg-gradient-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
              REVENAC
            </span>
          </div>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="/login" className="text-gray-600 hover:text-emerald-600 transition">
              Login
            </Link>
            <Link href="/register">
              <Button className="bg-emerald-600 hover:bg-emerald-700">
                Get Started
              </Button>
            </Link>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <div className="max-w-4xl mx-auto space-y-8">
          <h1 className="text-5xl md:text-7xl font-bold bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-600 bg-clip-text text-transparent">
            Turn Waste Into Rewards
          </h1>
          <p className="text-xl md:text-2xl text-gray-600">
            Recycle smarter with REVENAC. Deposit bottles, earn tokens, and make a real impact on the environment.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link href="/register">
              <Button size="lg" className="bg-emerald-600 hover:bg-emerald-700 text-lg px-8 py-6">
                Start Recycling
              </Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline" className="text-lg px-8 py-6 border-emerald-600 text-emerald-600 hover:bg-emerald-50">
                Sign In
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="container mx-auto px-4 py-20">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <FeatureCard
            icon={<QrCode className="w-12 h-12 text-emerald-600" />}
            title="Scan QR Code"
            description="Deposit recyclables and scan the QR code generated by the RVM"
          />
          <FeatureCard
            icon={<Leaf className="w-12 h-12 text-teal-600" />}
            title="Earn Tokens"
            description="Receive reward tokens instantly for every item you recycle"
          />
          <FeatureCard
            icon={<Trophy className="w-12 h-12 text-cyan-600" />}
            title="Join Leaderboard"
            description="Compete with others and become an eco-champion in your city"
          />
          <FeatureCard
            icon={<Gift className="w-12 h-12 text-emerald-600" />}
            title="Redeem Rewards"
            description="Exchange your tokens for vouchers, coupons, and exclusive offers"
          />
        </div>
      </section>

      {/* Impact Stats */}
      <section className="container mx-auto px-4 py-20">
        <div className="bg-gradient-to-r from-emerald-600 to-teal-600 rounded-3xl p-12 text-white">
          <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">
            Our Environmental Impact
          </h2>
          <div className="grid md:grid-cols-3 gap-8 text-center">
            <StatCard number="1M+" label="Bottles Recycled" />
            <StatCard number="50K+" label="Active Users" />
            <StatCard number="250T" label="CO₂ Saved (kg)" />
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4 text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Recycle className="w-6 h-6" />
            <span className="text-xl font-bold">REVENAC</span>
          </div>
          <p className="text-gray-400 mb-4">
            Smart Reverse Vending Machine Platform
          </p>
          <p className="text-sm text-gray-500">
            © 2025 REVENAC. All rights reserved. | Made for SIH 2025
          </p>
        </div>
      </footer>
    </div>
  )
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <div className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition transform hover:-translate-y-1">
      <div className="mb-4">{icon}</div>
      <h3 className="text-xl font-bold mb-2 text-gray-900">{title}</h3>
      <p className="text-gray-600">{description}</p>
    </div>
  )
}

function StatCard({ number, label }: { number: string; label: string }) {
  return (
    <div>
      <div className="text-5xl md:text-6xl font-bold mb-2">{number}</div>
      <div className="text-xl text-emerald-100">{label}</div>
    </div>
  )
}
